### ISSUE TITLE
nginx_tcp_proxy_module doesn't build with 1.2.7

### ISSUE THREAD

**Issue by vitalimt** [yaoweibin/nginx_tcp_proxy_module#68]
Errors:

/usr/ports/www/nginx/work/nginx_tcp_proxy_module-master-89a00de4b6/ngx_tcp_core_module.c: In function 'ngx_tcp_log_set_access_log':
/usr/ports/www/nginx/work/nginx_tcp_proxy_module-master-89a00de4b6/ngx_tcp_core_module.c:891: error: 'ngx_open_file_t' has no member named 'buffer'
/usr/ports/www/nginx/work/nginx_tcp_proxy_module-master-89a00de4b6/ngx_tcp_core_module.c:892: error: 'ngx_open_file_t' has no member named 'buffer'
/usr/ports/www/nginx/work/nginx_tcp_proxy_module-master-89a00de4b6/ngx_tcp_core_module.c:896: error: 'ngx_open_file_t' has no member named 'pos'
/usr/ports/www/nginx/work/nginx_tcp_proxy_module-master-89a00de4b6/ngx_tcp_core_module.c:896: error: 'ngx_open_file_t' has no member named 'buffer'
/usr/ports/www/nginx/work/nginx_tcp_proxy_module-master-89a00de4b6/ngx_tcp_core_module.c:897: error: 'ngx_open_file_t' has no member named 'last'
/usr/ports/www/nginx/work/nginx_tcp_proxy_module-master-89a00de4b6/ngx_tcp_core_module.c:897: error: 'ngx_open_file_t' has no member named 'buffer'
**\* [objs/addon/nginx_tcp_proxy_module-master-89a00de4b6/ngx_tcp_core_module.o] Error code 1

Solution:
Minimum Necessary Intrusion to make it build and work is as follows:

diff -r nginx_tcp_proxy_module-master-89a00de4b6.orig/ngx_tcp_core_module.c nginx_tcp_proxy_module-master-89a00de4b6.edited/ngx_tcp_core_module.c
796c796
## < #if (nginx_version) >= 1003010

> # if (nginx_version) >= 1002007
> 
> 850c850
> ## < #if (nginx_version) >= 1003010
> # if (nginx_version) >= 1002007
> 
> diff -r nginx_tcp_proxy_module-master-89a00de4b6.orig/ngx_tcp_log.c nginx_tcp_proxy_module-master-89a00de4b6.edited/ngx_tcp_log.c
> 23c23
> ## < #if (nginx_version) >= 1003010
> # if (nginx_version) >= 1002007
> 
> 69c69
> ## < #if (nginx_version) >= 1003010
> # if (nginx_version) >= 1002007
