### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by beedub** [yaoweibin/nginx_tcp_proxy_module#7]
I'm getting the following error on build in 0.8.54 (also just tried with 0.8.53).  Any ideas?

```
            -o objs/addon/yaoweibin-nginx_tcp_proxy_module-0d564d6/ngx_tcp_upstream.o \
            /usr/local/src/nginx_tcp_proxy_module/yaoweibin-nginx_tcp_proxy_module-0d564d6/ngx_tcp_upstream.c
```

make[1]: Leaving directory `/tmp/vagrant-chef/nginx-0.8.54'STDERR: /usr/local/src/nginx_tcp_proxy_module/yaoweibin-nginx_tcp_proxy_module-0d564d6/ngx_tcp_upstream.c: In function 'ngx_tcp_upstream_connect':
/usr/local/src/nginx_tcp_proxy_module/yaoweibin-nginx_tcp_proxy_module-0d564d6/ngx_tcp_upstream.c:355: error: 'ngx_peer_connection_t' has no member named 'check_index'
/usr/local/src/nginx_tcp_proxy_module/yaoweibin-nginx_tcp_proxy_module-0d564d6/ngx_tcp_upstream.c:356: error: 'ngx_peer_connection_t' has no member named 'check_index'
/usr/local/src/nginx_tcp_proxy_module/yaoweibin-nginx_tcp_proxy_module-0d564d6/ngx_tcp_upstream.c: In function 'ngx_tcp_upstream_finalize_session':
/usr/local/src/nginx_tcp_proxy_module/yaoweibin-nginx_tcp_proxy_module-0d564d6/ngx_tcp_upstream.c:551: error: 'ngx_peer_connection_t' has no member named 'check_index'
/usr/local/src/nginx_tcp_proxy_module/yaoweibin-nginx_tcp_proxy_module-0d564d6/ngx_tcp_upstream.c:552: error: 'ngx_peer_connection_t' has no member named 'check_index'
/usr/local/src/nginx_tcp_proxy_module/yaoweibin-nginx_tcp_proxy_module-0d564d6/ngx_tcp_upstream.c:553: error: 'ngx_peer_connection_t' has no member named 'check_index'
make[1]: **\* [objs/addon/yaoweibin-nginx_tcp_proxy_module-0d564d6/ngx_tcp_upstream.o] Error 1
